name: Hello World
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest    #where should this job runs
    steps: 
      - name: Hello Step
        run: |
          echo "this is line one"
          echo "this is line two"
        
