name: Inputs Demo
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Choose the environment to deploy
        required: true
        default: dev
        options:
          - dev
          - test
          - prod
      artifact_tag:
        description: Choose the git tag to deploy
        required: true
jobs:
  inputs-demo:
    runs-on: ubuntu-latest
    steps:
     - name: Deploy the App
       run: echo "Deploy the ${{ inputs.artifacts_tag }} application to ${{ inputs.environment }}"
