name: Outputs Demo
on: push
jobs:
  build:
    outputs:
      version: ${{ steps.step1.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Build Test
        id: step1
        run: echo "version=0.0.1" >> $GITHUB_OUTPUT
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the App
        run: echo "We are deploying the app with version ${{ needs.build.outputs.version }}"
  
